
<div class="row">
    <span class="span8 pull-left">
        <h3>
            <?= ($this->account->getParent() ?
                '<a href="/accounts/view/' . $this->account->getParent()->getId() . '">' .
                $this->account->getParent()->getName() . '</a> / ' : '') .
            $this->account->getName() ?>
        </h3>
    </span>
    <span class="span4 pull-right align-right">
        <h4><?= $this->formatCurrency($this->balance) ?></h4>
    </span>
</div>

<div class="row">
    <span class="span8">
        <h4>Transactions</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th class="align-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $split): ?>
                    <tr>
                        <td><?= $split->getTransaction()->getPosted()->format('m/d/Y') ?></td>
                        <td><?= $split->getTransaction()->getDescription() ?></td>
                        <td class="align-right"><?= $this->formatCurrency($split->getValue()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?= $this->paginationControl(
            $this->paginator,
            'Sliding',
            'layout/pagination',
            ['route' => 'accounts/view-account', 'routeParams' => ['id' => $this->account->getId()]]
        ) ?>
    </span>
    <span class="span4">
        <?php if ($this->account->getType() == 'EXPENSE'): ?>
        <h4>Average Monthly Spend</h4>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Month</th>
                    <th class="align-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->monthStats as $month): ?>
                    <tr>
                        <td><?= date('F Y', strtotime($month['month'] . '-01')) ?></td>
                        <td class="align-right"><?= $this->formatCurrency($month['amount']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>
    </span>
</div>
