<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GnuCash')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/gnucash.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <?= $this->headScript()->prependFile('/js/bootstrap.min.js')->prependFile('/js/jquery-2.0.2.min.js') ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">GnuCash</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
