<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('GnuCash')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/gnucash.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <?= $this->headScript()->prependFile('/js/bootstrap.min.js')->prependFile('/js/jquery-2.0.2.min.js') ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?= $this->url('home') ?>">GnuCash</a>
                    <div class="nav-collapse collapse">
                        <?= $this->navigation('Navigation')->menu()->setPartial(
                            ['application/layout/menu', 'default']
                        ) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
