
<ul class="stats-container">
    <?php foreach ($this->snapshots as $snapshot): ?>
        <li>
            <a href="#" class="stat summary">
                <img src="<?= $snapshot['icon'] ?>" />
            <span class="digit">
                <span class="text"><?= $snapshot['title'] ?></span>
                <?= $this->formatCurrency($snapshot['amount'], 0) ?>
            </span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>

<!--
<div class="row">
    <div class="span3" style="-moz-box-sizing: border-box; box-sizing: border-box; border-right: 1px solid #e0e0e0;">
        <h3 style="margin-top: 0; padding-top: 0; font-size: 14pt; line-height: 14pt">Accounts</h3>
    </div>
    <div class="span9" style="-moz-box-sizing: border-box; box-sizing: border-box;">
        <h3 style="margin-top: 0; padding-top: 0; font-size: 14pt; line-height: 14pt">Budget for June 2013</h3>
    </div>
</div>
-->